### ISSUE TITLE
Blind

### ISSUE THREAD

**Issue by Haileselasie** [KaeruTeam/duel-issue-tracker#19] opened 2020-10-14 18:46 UTC
It should move the Pokemon 1-2 steps away but right now it just freezes

![Screen_Recording_20201014-144146_Pokmon Duel_1](https://user-images.githubusercontent.com/72710530/96031686-b2bc4e80-0e2b-11eb-9ba1-97e10c03e70c.gif)
![VideoCapture_20201014-144435](https://user-images.githubusercontent.com/72710530/96031779-cf588680-0e2b-11eb-909a-a9dc01657054.jpg)

**Comment by shutterbug2000** [comment] 2020-10-15 05:29
Duplicate of #7. Thank you for your report however!

**Closed as completed by shutterbug2000** 2020-10-15 05:29 UTC
Labels: bug, duplicate, Blue Move, Never-ending turn
